services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870  # Порт веб-интерфейса HDFS
      - 9000:9000  # Порт RPC для взаимодействия с DataNode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name  # Том для хранения метаданных HDFS
      - ./podcasts.csv:/podcasts.csv 
    environment:
      - CLUSTER_NAME=test  # Имя кластера
    env_file:
      - ./hadoop.env  # Файл с переменными окружения
    deploy:
      resources:
        limits:
          memory: 512M    # Ограничение на память

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data  # Том для хранения данных HDFS
    environment:
      SERVICE_PRECONDITION: "namenode:9870"  # Ожидание старта NameNode
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          memory: 512M    # Ограничение на память

  spark:
    image: bitnami/spark:latest  # Используем образ Spark
    container_name: spark
    depends_on:
      - namenode  # Ожидает, пока NameNode будет готов
    volumes:
      - ./podcasts.csv:/podcasts.csv  # Делаем доступным podcasts.csv в контейнере
      - ./Spark_application.py:/app/Spark_application.py  # Монтируем скрипт с задачей
    environment:
      - SPARK_MASTER=spark://spark:7077  # Указываем Spark master
    entrypoint: ["/bin/bash", "-c", "while :; do sleep 1000; done"]  # Просто держим контейнер в живых

volumes:
  hadoop_namenode:
  hadoop_datanode1: